### PR TITLE
Add FIR, the Flang project's IR, to the dialect registry.

### PR DESCRIPTION
**Pull request by schweitzpgi**

### CODE REVIEW

**Comment by schweitzpgi** [comment]
Nvidia has signed the CLA.

@googlebot I signed it!

**Comment by joker-eph** [comment]
(Overriding the CLA on account of a contribution from Nvidia)

**Comment by schweitzpgi** [comment]
I am unclear on what happened here. Why did the bot reject this simple change?

**Comment by joker-eph** [comment]
It didn’t reject: the PR was closed by the commit linked in the closing message (you commit was merged internally in Google and then mirrored to GitHub, our tooling added “Closes #62” to the commit message so that it links this PR to the commit, and GitHub automatically closes the PR)

**Pull request closed without merging**
