### PR TITLE
Unify vector op names with other dialects.

### PR DESCRIPTION
**Pull request by Kayjukh**
Change vector op names from `VectorFooOp` to `Vector_FooOp` and from `vector::VectorFooOp` to `vector::FooOp`.

### CODE REVIEW

**Comment by Kayjukh** [comment]
I just followed what was done in commit 1e9bdfc for the GPU dialect. It might be a better fit since it avoids the redundant dialect name in the operation.

**Comment by nicolasvasilache** [comment]
Please rebase on 3f37f5278b304fdf79b9f56d625b39e9c9d21b96 and I'll start the integration process.

**Comment by Kayjukh** [comment]
I just rebased on the latest commit on master c203743.

**Comment by nicolasvasilache** [comment]
can you please rebase and make sure to run clang-format?
The following 3 files are flagged:
include/mlir/EDSC/Intrinsics.h
lib/Conversion/VectorConversions/VectorToVector.cpp
lib/Transforms/MaterializeVectors.cpp

**Comment by Kayjukh** [comment]
I just rebased and ran `clang-format`, but it does not find anything to format. Could this be a version mismatch? I'm using
```
clang-format version 9.0.0 (tags/RELEASE_900/final)
```

**Comment by ftynse** [comment]
I ran `clang-format -i -style=file` on your changes, there was a bunch of those. On the general basis, we are using clang-format compiled from LLVM's HEAD.

**Comment by Kayjukh** [comment]
@nicolasvasilache Interestingly enough, I cannot manage to get any format changes from the files you pointed out to me.

@ftynse However, if I run
```sh
find . -name "*.cpp" | xargs clang-format -i -style=file
find . -name "*.h" | xargs clang-format -i -style=file
```
in the root of the repository, it changes a lot of files, most of which I did not even touch. A quick `git diff` shows that these changes are mostly related to the [`AlwaysBreakTemplateDeclarations: Yes`](https://github.com/tensorflow/mlir/blob/master/.clang-format#L2) in the `.clang-format` file. Are we using the same `.clang-format`?

**Pull request closed without merging**
