### PR TITLE
[README] Minor edits.

### PR DESCRIPTION
**Pull request by dan-zheng**
Use standard "TensorFlow" spelling.

### CODE REVIEW

**Comment by dan-zheng** [comment]
There are no other usages of "Tensorflow":
```
$ grep -nr "Tensorflow" .
./README.md:11:Tensorflow compilers we are building on top of MLIR will be part of the
./README.md:12:main Tensorflow repository soon.
```

**Comment by joker-eph** [comment]
Thanks Dan, please note: https://github.com/tensorflow/mlir/blob/master/CONTRIBUTING.md

(You can send a CL though)

**Comment by dan-zheng** [comment]
Apologies! I should've been more careful.

**Comment by dan-zheng** [comment]
Done in https://github.com/tensorflow/mlir/commit/76b7b39e20b50fd770a6c93f2f7600fc7120a968.

**Pull request closed without merging**
