### PR TITLE
[Linalg] Change attribute n_loop_types to iterator

### PR DESCRIPTION
**Pull request by tetuante**
This addresses issue #270. Linalg is updated to take the same form
of iterator_types than vector contraction.

Change-Id: Iedae21efded776e65a43b2df2043cd981644b213

### CODE REVIEW

**Comment by tetuante** [comment]
@googlebot I signed it!

**Comment by nicolasvasilache** [comment]
You will need to sign the CLA to merge this.
Thanks!

**Comment by tetuante** [comment]
@googlebot I fixed it.

**Comment by tetuante** [comment]
@googlebot I fixed it.

**Comment by tetuante** [comment]
@googlebot I signed it!

**Comment by nicolasvasilache** [comment]
Trying to remove the CLA:no label and see if it retriggers a check somehow.
Sorry this is so painful..
Quick question, are you using a corporate address and maybe this detects that there must be a company-wide CLA?

**Comment by tetuante** [comment]
The first time I guess a I signed the CLA with my personal gmail account but committed with my university one. Then, I signed another CLA with my university email , which is the one I use in github..... I don't think my university (UCM) is asks for company-wide CLA. I will try to figure it out

**Comment by tetuante** [comment]
@googlebot I fixed it.

**Comment by tetuante** [comment]
talking to the bot triggered the checking again...and was not succesful. Is there a way to know if it is about the university CLA?

**Comment by nicolasvasilache** [comment]
I'll ask internally, could you maybe try a new PR duplicate of this one see if it helps that you have signed the CLA before sending the PR?
Also, is the email on which we communicated the proper one?

**Comment by tetuante** [comment]
@googlebot I fixed it.

**Comment by tetuante** [comment]
I will try a new PR then. Yes, my primary email in github is the same we have been using to communicate last week. I tried to add my other email as a valid email in my GitHub account, but I guess "googlebot" is checking the email of the commit

**Comment by tetuante** [comment]
I cannot create a new Pull Request from the same branch in my forked repo; GitHub detects it is actually this one and redirects me here. Shall I close this one and start again?

**Comment by joker-eph** [comment]
The problem is that the email used for the commit is @arm.com ; if you're contributing as part of your contract with ARM then you may need to synchronize with them for signing the CLA.

**Comment by tetuante** [comment]
@arm?? No, no.  It was my mistake then! I was trying to commit with my @ucm account. Indeed, I don't have @arm address in GitHub! Ok, I will see what I did wrong. But then, I guess it is better to close this request and start a new one

**Pull request closed without merging**
